#PBS -A GT-tf74
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=64gb
#PBS -m abe
#PBS -o contact-loss.out
#PBS -e contact-loss.error
#PBS -M emolel3@gatech.edu

echo "Started on `/bin/hostname`"
cd /storage/coda1/p-tf74/0/shared/leshinka/ && . ./spack/share/spack/setup-env.sh && spack env activate fenicsx-env

export PYTHONPATH=$PYTHONPATH:/storage/coda1/p-tf74/0/shared/leshinka/opt/
export PATH=$PATH:/storage/coda1/p-tf74/0/shared/leshinka/opt/

cd /storage/coda1/p-tf74/0/shared/leshinka/ssb/

python3 contact_loss.py 101-101-101 segmented/000.tif
