#PBS -A GT-tf74
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=64gb
#PBS -m abe
#PBS -o current-constriction.out
#PBS -e current-constriction.error
#PBS -M emolel3@gatech.edu

echo "Started on `/bin/hostname`"
cd /storage/coda1/p-tf74/0/shared/leshinka/ && . ./spack/share/spack/setup-env.sh && spack env activate fenicsx-env

export PYTHONPATH=$PYTHONPATH:/storage/coda1/p-tf74/0/shared/leshinka/opt/
export PATH=$PATH:/storage/coda1/p-tf74/0/shared/leshinka/opt/:/storage/home/hcoda1/0/emolel3/.local/

cd /storage/coda1/p-tf74/0/shared/leshinka/ssb/

mpirun -n 1 ./current_constriction_3d.py --grid_size 100-100-100 --data_dir mesh/1/101-101-101_current-constriction/ --eps 0.15
