#PBS -A GT-tf74
#PBS -l walltime=120:00:00
#PBS -l nodes=1:ppn=4
#PBS -l pmem=64gb
#PBS -m abe
#PBS -o mesher.out
#PBS -e mesher.error
#PBS -M emolel3@gatech.edu

echo "Started on `/bin/hostname`"
cd $PBS_O_WORKDIR
. /storage/home/hcoda1/0/emolel3/p-tf74-0/spack/share/spack/setup-env.sh
spack env activate fenicsx-env

python3 mesher.py --img_folder Archive/electrolyte --grid_info 101-101-101 --origin 0,0,0
