#PBS -A GT-tf74
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=64gb
#PBS -m abe
#PBS -o packed-spheres.out
#PBS -e packed-spheres.error
#PBS -M emolel3@gatech.edu

echo "Started on `/bin/hostname`"
module load anaconda3/2020.11
conda activate fenicsx-env

cd /storage/coda1/p-tf74/0/shared/leshinka/ssb/

mpirun -n 1 ./transport.py --grid_size 1-1-1 --data_dir mesh/packed_spheres/1-1-1_30/
