#PBS -A GT-tf74
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=64gb
#PBS -m abe
#PBS -o run.out
#PBS -e run.error
#PBS -M emolel3@gatech.edu

echo "Started on `/bin/hostname`"
cd /storage/coda1/p-tf74/0/shared/leshinka/ssb
. /storage/coda1/p-tf74/0/emolel3/spack/share/spack/setup-env.sh
spack env activate fenicsx-env

./mesher.py --img_folder Archive/electrolyte --grid_info 51-51-51 --origin $1,$2,$3 && mpirun -np 2 ./transport.py --grid_info 51-51-51 --origin $1,$2,$3
