#PBS -A GT-tf74
#PBS -l walltime=1:30:00
#PBS -l nodes=2:ppn=8
#PBS -l pmem=32gb
#PBS -m abe
#PBS -q inferno
#PBS -j oe
#PBS -o transport.out
#PBS -M emolel3@gatech.edu

module load python/3.7.4

cd $PBS_O_WORKDIR

echo "Started on `/bin/hostname`"
chmod +x geometry.py
./geometry.py --img_sub_dir segim --grid_info 201-201-201

chmod +x transport.py
./transport.py --working_dir=$PBS_O_WORKDIR --grid_info=201-201-201
