#PBS -A GT-tf74
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=192gb
#PBS -m abe
#PBS -o transport.out
#PBS -e transport.error
#PBS -M emolel3@gatech.edu


cd $PBS_O_WORKDIR
echo "Started on `/bin/hostname`"
. /storage/home/hcoda1/0/emolel3/p-tf74-0/spack/share/spack/setup-env.sh
spack env activate fenicsx-env
spack load py-fenics-dolfinx@main
spack load petsc@3.17.1

mpiexec ./transport.py --grid_info 51-51-51 --origin 0,0,0
