#PBS -A GT-tf74
#PBS -l walltime=24:00:00
#PBS -l nodes=4:ppn=4
#PBS -l mem=192gb
#PBS -m abe
#PBS -q inferno
#PBS -o transport.out
#PBS -e transport.error
#PBS -M emolel3@gatech.edu


cd $PBS_O_WORKDIR
. /storage/home/hcoda1/0/emolel3/p-tf74-0/spack/share/spack/setup-env.sh
spack env activate fenicsx-env
spack load py-fenics-dolfinx@main

mpirun --malloc_debug ./transport.py --grid_info 51-51-51 --origin 0,0,0
