- name: Installation of Packages
  hosts: virtualmachines
  tasks:
   - name: Install APT Packages
     apt:
      pkg:
      - mariadb-client
      - mariadb-server
      - libnvidia-compute-530
      - nvidia-driver-530
      - paraview
      - python3-dev
      - slurmctld
      - slurmd